[package]
name = "rust_relay"
version = "0.1.0"
edition = "2024"

[dependencies]
config = "0.15.19"
env_logger = "0.11.8"
gpiocdev = "0.8.0"
log = "0.4.29"
surge-ping = "0.8.4"
tokio = { version = "1.49.0", features = ["full"] }
